### ISSUE TITLE
Master branch contains the solution code

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/rails-refactoring-apis#12]
Maybe I'm missing something — otherwise, I've no idea why this wasn't reported before — but all that's currently required to pass this 'lab' is adding a `.env` file w/ your GitHub client ID + secret.

**Comment by steveafrost** [comment]
Yeah... it seems like the instructions want you to refactor the API code but that code is already halfway refactored. The GitHub service and model have been setup but the controllers haven't been refactored yet.

All tests pass out the gate once you add the .env @gj mentioned.

**Comment by jcpny1** [comment]
Compete solution is in master branch (except for .env as previously noted).

**Comment by drakeltheryuujin** [comment]
We're aware of this and are tracking it in issue #48. 

We are in the process of updating the materials in this section and will
be rewriting this lesson to address the current issues. We'll be taking
all of this information into consideration in upcoming releases of this
curriculum.
