### ISSUE TITLE
Items 2, 4, and 5 from readme are complete

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/rails-refactoring-apis#13]
All tests pass when lab is forked. 

This is not good (even though this is a refactoring lab) because some of these tests specifically have to do with the new design pattern.

Items 2, 4, and 5 from the readme are already implemented.

This issue was originally raised by @lair001

**Comment by gj** [comment]
@aturkewi: https://github.com/learn-co-curriculum/rails-refactoring-apis/issues/12

**Comment by gj** [comment]
And https://github.com/learn-co-curriculum/rails-refactoring-apis/issues/8 + https://github.com/learn-co-curriculum/rails-refactoring-apis/issues/5

**Comment by drakeltheryuujin** [comment]
We're aware of this and are tracking it in issue #48. 

We are in the process of updating the materials in this section and will
be rewriting this lesson to address the current issues. We'll be taking
all of this information into consideration in upcoming releases of this
curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.
