### ISSUE TITLE
When I forked and cloned this repo, most of the tests were already passing

### ISSUE THREAD

**Issue by ldgarber** [learn-co-curriculum/rails-refactoring-apis#14]
The code seems to be already refactored. 3 tests are still failing, so maybe it's ok, but it looks like most of it is done already

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
