### ISSUE TITLE
Lab forks branch with nearly all of the solution

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/rails-refactoring-apis#15]
I forked the lab and almost everything the README says to do is already done. The only failing tests are failing because the stubbed requests aren't working correctly.

**Comment by mikeries** [comment]
In my case, all I had to do was change the names of my environment variables to match what the spec_helper expected.  Then all the tests passed.

**Comment by itzsaga** [comment]
All my tests passed without changing anything. Literally, no changes.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
