### ISSUE TITLE
web-console is interfering with the specs running properly

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-curriculum/rails-refactoring-apis#16]
I've run into this issue a couple of times in the past week with students (and myself when I did the lab myself a year ago). Sorry it took so long to get this issue to the right place!

Fix is pretty simple, just need to move web-console to development group only and it works fine.

**Comment by itzsaga** [comment]
I hit this in MANY labs. Haven't raised issues on all of them though. Luckily, `rspec` tells you exactly what to do. Not sure if `learn` does.

**Comment by itzsaga** [comment]
Also mentioned in #9

**Comment by DakotaLMartinez** [comment]
agreed, not the hardest error to fix if you know how to read it, but easy enough to create a quick PR and merge to fix it 👍
