### ISSUE TITLE
Master branch has all the solutions

### ISSUE THREAD

**Issue by sarjumulmi** [learn-co-curriculum/rails-refactoring-apis#18]
New fork from master has all the solutions and passes all the tests.

**Comment by mdjurdj1** [comment]
@avidor Just spoke with this student and can confirm they were able to pass all tests by forking the lab and changing a `.env` variable. PRs for the lab seem to suggest varying levels of work needed to complete it, but not what I'd expect. Would check this lab to be sure it works as expected

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
