### ISSUE TITLE
"WebMock unable to make HTTP Requests, please stub out the request another way instead..."

### ISSUE THREAD

**Issue by mdjurdj1** [learn-co-curriculum/rails-refactoring-apis#19]
Student presented this issue today as a recurring error they'd been seeing in their WebMock-based labs. This error results from WebMock's default behavior prohibiting actual HTTP requests from being made to localhost. Though there is a line of code at the bottom of our spec_helper configuration which is supposed to override WM's default behavior and allow real requests: `WebMock.disable_net_connect!(:allow_localhost => true)`, student still saw these errors.

For whatever reason, moving the logic of overriding WebMock's default settings into the rspec config block, and then globally enabling net requests seemed to fix the error. Here is the code which satisfied WebMock:

```
#spec_helper.rb

RSpec.configure do |config|
  config.before(:all, type: :request) do
    WebMock.allow_net_connect!
  end  

...<insert rest of settings after>
```

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #48.

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
