### ISSUE TITLE
Solution branch does not match directions

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/rails-refactoring-apis#21]
@Lukeghenco 
The solution branch for this repo does not use the `GithubService` object in the controllers. It also does not reflect part 5 of the directions, " Follow the path laid out in the tests, and get the application refactored and working. You will have to change the ERB file as well as your #logged_in? method."

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #48. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
