### ISSUE TITLE
I somehow got the solution branch when I forked and cloned this repo... solution is also broken

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/rails-refactoring-apis#22]
As the subject line says, I somehow got the solution branch after running learn open.

The same error that rendered the last github lab test broken appears here.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
