### ISSUE TITLE
Lab comes completed

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/rails-refactoring-apis#24]
Adding the .env file makes all tests pass. You are supposed to create a service file and refactor controllers, but all that comes pre-completed.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
