### ISSUE TITLE
Confirming whether instruction is accurate

### ISSUE THREAD

**Issue by dtow55** [learn-co-curriculum/rails-refactoring-apis#26]
One of the instructions in this lab is: ' _You will have to change the ERB file as well as your #logged_in? method_.'.  However, I could not think of any reason to change the ERB or the #logged_in? function, and got all tests passing without doing so. I also checked with one of the coaches and they said the solution does not change that method vs. the original.
Wanted to just raise this so it can be confirmed.

Additionally, the GithubRepo class in this lab has an #initialize method: 
  _def initialize(hash)
    @name = hash["name"]
    @url = hash["html_url"]
  end_
And I'm just not really sure what the purpose of it was... I completed the lab with just initializing all instances with blank @name and @url. Just wanted to confirm whether this was still necessary for the lab.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in issue #48. 

We will add this to our internal work queue.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues. We'll be taking all of this information into consideration in upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify you when it is resolved.

Thanks for contributing!
