### ISSUE TITLE
Solution is just like master and doesn't refactor at all.

### ISSUE THREAD

**Issue by efl7a** [learn-co-curriculum/rails-refactoring-apis#27]
I was looking forward to seeing what I had done wrong as I had to comment out the authentication test after refactoring the repositories#index as it kept giving Web:Mock errors.

**Comment by drakeltheryuujin** [comment]
Hi @efl7a ,

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues. We'll take this information into consideration in upcoming releases of this curriculum.

Thanks for contributing! 💙
