### ISSUE TITLE
Students need more guidance

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/rails-refactoring-apis#28]
@weezwo 
Students need much more guidance than is given to complete this lab. We should probably add additional instructions to interpret the errors regarding the request stubs, or give very specific instructions as to how the requests should be written (send x,y,z parameters in body of the request, pass token through header, etc.). 

This lab kind of throws students into the deep end (is that the right expression?)

**Comment by weezwo** [comment]
Hi, @kwebster2 ! Thanks for bringing this issue to my attention. This lab is actually in the JS project section, so I'm going to tag @cernanb and bring him into the conversation.

**Comment by drakeltheryuujin** [comment]
Hi @kwebster2 ,

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues. We'll take this information into consideration in upcoming releases of this lab.

Thanks for contributing! 💙
