### ISSUE TITLE
It looks like the solution is already coded

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/rails-refactoring-apis#29]
All tests are passing once I add .env with valid keys.

I simply refactored the code in the controllers to use the methods from the GithubService class. But all the tests were passing even without that. Even the solution branch doesn't have the code refactored in the controllers...

**Comment by drakeltheryuujin** [comment]
Hi @Ary770  ,

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues. We'll take this information into consideration in upcoming releases of this curriculum.

Thanks for contributing! 💙
