### ISSUE TITLE
Solution already given

### ISSUE THREAD

**Issue by IngridWong0715** [learn-co-curriculum/rails-refactoring-apis#30]
All the codes are already provided: the only thing needed to make the remaining tests (3 out of 14) pass is to add the client_id and secret inside .env

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
