### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/rails-refactoring-apis#32]
I'm getting the same routing error when I run the tests for this lab as I got with the Working With APIs lab:
 Failure/Error: visit root_path
     ActionController::RoutingError:
       No route matches [GET] "/login/oauth/authorize"

Everything is working fine in the browser

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
