### ISSUE TITLE
tests fail to find root after solution

### ISSUE THREAD

**Issue by joeymariano** [learn-co-curriculum/rails-refactoring-apis#34]
https://github.com/nmlstyl/rails-refactoring-apis-v-000  <<  working solution with the tests complaining about not finding the route

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
