### ISSUE TITLE
Frustrating lab

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/rails-refactoring-apis#37]
1. Most of the directions are already executed in the forked code, despite the directions. Other issues have been raised about this. 
2. I really want to learn and drill API calls, and this section has been so frustrating. There's hardly one lab that reaches the level of the ruby/rails labs, the tech coaches aren't all that helpful on this stuff, and it has left me and other students very frustrated. This lab needs to be rethought from the start.

**Comment by asabogal** [comment]
Completely agree! 
This whole section, including many parts of JS need a lot of work and guidance.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We've updated the materials and we'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
