### ISSUE TITLE
Same issue since 2016!

### ISSUE THREAD

**Issue by asabogal** [learn-co-curriculum/rails-refactoring-apis#40]
The solution is included in the repo. This has been pointed out since 2016 and it hasn't been corrected in more than 2 years?? 

Also the repo is not compatible with certain gems included and the gem installers fail.
Instructions are vague and not directed.

This whole section needs more guidance. Including the JS section.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have removed the solution from master. We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues. We'll take this information into consideration in upcoming releases of this curriculum.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
