### ISSUE TITLE
Having Issues with WebMock not recognizing a get request.

### ISSUE THREAD

**Issue by anikonchuk** [learn-co-curriculum/rails-refactoring-apis#41]
Even with the code that has been provided, WebMock still throws up an error specifically for spec/03_features/repos_spec line 5. 

The specific error being thrown is: 
`Failure/Error:
       response = Faraday.post "https://github.com/login/oauth/access_token",
           {client_id: client_id, client_secret: client_secret, code: code},
           {'Accept' => 'application/json'}`
     
    ` WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: POST https://github.com/login/oauth/access_token with body 'client_id=98576fc02000c7415025&client_secret=c723b52177038e0a35a5bf8eaf4f72a4930d3152&code=20' with headers {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Type'=>'application/x-www-form-urlencoded', 'User-Agent'=>'Faraday v0.15.4'}
`

**Comment by cdcardle** [comment]
I had this issue until I created a .env file and put in the github app client id and secret.
Hopefully this helps!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #48.

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
