### ISSUE TITLE
Bundle Issues

### ISSUE THREAD

**Issue by charmcity-code** [learn-co-curriculum/rails-refactoring-apis#43]
I had issues with bundle install for this lab and this fixed it

1. Delete gemfile.lock ifit is present (if not, do not worry) 
2. Place this in gemfile: gem 'bundler', '~> 1.16', '>= 1.16.1' 
3. from the command line run this: gem install bundler -v 1.16.1 
4. from the command line run this: bundle _1.16.1_ install 
5. now learn commands should work

then got an sqlite3 error which was fixed by changing gem 'sqlite3' to gem 'sqlite3', '~> 1.3.7'

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #48.

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
