### ISSUE TITLE
Still nobody looking at fixing this? Solution Provided.

### ISSUE THREAD

**Issue by FionaDL** [learn-co-curriculum/rails-refactoring-apis#45]
The API section has been very muddled, and often times the instructions don't really coincide with the test. The first lesson in the section was great, but after that everything became muddled.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and the solution is removed from master.
We'll take your other feedback into consideration in upcoming releases of this curriculum.
Thanks for contributing! 💙
