### ISSUE TITLE
Solution provided + still need to refactor + Webmock error

### ISSUE THREAD

**Issue by catherinism** [learn-co-curriculum/rails-refactoring-apis#47]
The solution may have been provided but some files still need to be refactored like in the previous code along lab [Web Service Objects](https://github.com/learn-co-students/web-service-objects-readme-v-000). 

Once you refactor, you may encounter WebMock::NetConnectNotAllowedError. Renaming my GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET into **GITHUB_CLIENT** and **GITHUB_SECRET** seemed to fix the issue. Hopefully this helps.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #48. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
