### ISSUE TITLE
Instruction #5

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-refactoring-apis#5]
Instruction no. 5 of the reame reads:

> ... Follow the path laid out in the tests, and get the application refactored and working. You will have to change the ERB file as well as your #logged_in? method.

but the solution I coded didn't require any changes to the #logged_in? method. After completion, I checked the answer, and it was not changed there either: 

https://github.com/learn-co-students/rails-refactoring-apis-v-000/blob/solution/app/controllers/application_controller.rb

**Comment by AnnJohn** [comment]
hi @onyoo is this related to the fact that the default branch had the solution on it already. Does having the default branch changed fix this issue? thanks!

**Comment by onyoo** [comment]
Hey @AnnJohn, I think the solution is there in both the maser branch and solution. This doesn't seem like a very big deal though. I think we are supposed to code it. I could be wrong. Sorry, looking back, this issue was kinda vague.

<img width="1022" alt="screen shot 2016-03-25 at 4 29 52 pm" src="https://cloud.githubusercontent.com/assets/14326883/14047365/c61dbe90-f2a7-11e5-9bd0-d5d327d4b5b4.png">
<img width="1021" alt="screen shot 2016-03-25 at 4 30 06 pm" src="https://cloud.githubusercontent.com/assets/14326883/14047367/c73a8d94-f2a7-11e5-8226-6b3eb3a235b7.png">

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.

We are in the process of updating the materials in this section and will be
rewriting this lesson to address the current issues. We'll be taking all of
this information into consideration in upcoming releases of this curriculum.
