### ISSUE TITLE
Rails server exiting instead of running

### ISSUE THREAD

**Issue by Marie-Burns22** [learn-co-curriculum/rails-refactoring-apis#50]
`rails s` would not run.

A tech coach had me comment out a line in the development.rb file and then it worked:
`config` folder
`environments` folder
`development.rb`
comment out line 31 `config.middleware.use RackSessionAccess::Middleware`

Thanks Dominique!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
