### ISSUE TITLE
Solution Forked?

### ISSUE THREAD

**Issue by ShanaLMoore** [learn-co-curriculum/rails-refactoring-apis#7]
I think I  may have downloaded the solution? All the tests pass and everything is already done via the instructions, unless I'm missing the point. When I tried to push it back to github, manually too, I get an error. 

------LEARN  COMMAND ------
Shana: rails-refactoring-apis-v-000
♥ learn

GithubRepo
  initialization with hash
    sets key 'name' to @name
    sets key 'html_url' to @url

GithubService
  initialization
    can be initialized without an `access_hash`
    can be initialized with an `access_hash`
  #authenticate!
    sends the correct POST request
    sets @access_token for a GithubService
  #get_username
    sends the correct GET request
    returns the username
  #get_repos
    sends the correct GET request
    returns an array of GithubRepo objects
  #create_repo
    sends the correct POST request

Features
  authentication
    displays the username on the page
  visiting root
    lists repos
  new repo form
    creates a new repo

Finished in 4.18 seconds (files took 4.47 seconds to load)
14 examples, 0 failures

---- LEARN SUBMIT COMMAND ----
Shana: rails-refactoring-apis-v-000
♥ learn submit
Adding changes...
Committing changes...
Pushing changes to GitHub...
/Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command': git '--git-dir=/Users/Shana/Development/code/rails-refactoring-apis-v-000/.git' '--work-tree=/Users/Shana/Development/code/rails-refactoring-apis-v-000' push 'origin' 'master'  2>&1:error: src refspec master does not match any. (Git::GitExecuteError)
error: failed to push some refs to 'git@github.com:ShanaLMoore/rails-refactoring-apis-v-000.git'
    from /Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/git-1.2.9.1/lib/git/lib.rb:727:in`push'
    from /Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/git-1.2.9.1/lib/git/base.rb:329:in `push'
    from /Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:123:in`block in push!'
    from /Users/Shana/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
    from /Users/Shana/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in`block in catch'
    from /Users/Shana/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
    from /Users/Shana/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in`catch'
    from /Users/Shana/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
    from /Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:122:in`push!'
    from /Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:23:in `commit_and_push'
    from /Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:46:in`commit_and_push!'
    from /Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:22:in `create'
    from /Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:6:in`create'
    from /Users/Shana/.rvm/gems/ruby-2.2.1@global/gems/learn-submit-1.1.7/bin/learn-submit:15:in `<top (required)>'
    from /Users/Shana/.rbenv/versions/2.2.2/bin/learn-submit:23:in`load'
    from /Users/Shana/.rbenv/versions/2.2.2/bin/learn-submit:23:in `<main>'
Shana: rails-refactoring-apis-v-000
♥

**Comment by JVThomas** [comment]
Same. To be specific, lab is making us fork the master-fix branch, which seems to have the solution coded for the service model (implementation into controller still needs to be done by student). Since master-fix is the only available branch, switching to master is not an option, though it wouldn't be much of a difference since the master branch recently merged with master-fix (as seen on Github).

Either fix the branch or adjust the README to reflect the current situation.

**Comment by dannyd4315** [comment]
Same issue here

**Comment by AnnJohn** [comment]
thanks all and sorry about this issue. It was a deployment issue but we updated the default branch to now be Master. Thanks again.
