### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/rails-refactoring-apis#8]
I'm not entirely sure, there are failing tests in this lesson, but most of everything seems to already of been done in the lesson....

**Comment by Enoch2k2** [comment]
Sorry this is for the rails-refactoring-apis lab.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
